In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv("/home/ctchervenkov/git/JA_Mobility_exchange/BEDDEM-MATSIM/01-disaggregatedvehiclestock.2018.csv")
df2 = pd.read_csv("/home/ctchervenkov/git/JA_Mobility_exchange/BEDDEM-MATSIM/02-sharing.2018.csv")
df3 = pd.read_csv("/home/ctchervenkov/git/JA_Mobility_exchange/BEDDEM-MATSIM/03-trips.2018.csv")

In [13]:
df1.head(20)

,ID,Type_Of_Vehicle,Powertrain,Cons,CO2,Year_Of_Immatriculation,Year_Of_Purchase,Weight_To_Universe
0,258237,Family car,D,0.05,127.250000,2014,2018,999.895675
1,258237,SUV - compact,GSL,0.05,128.200000,2010,2013,999.895675
2,258237,Bike (low price),NM,0.00,0.000000,2014,2010,999.895675
3,236370,SUV-normal,GSL,0.06,164.064516,2016,2012,3148.537084
4,236370,Bike (low price),NM,0.00,0.000000,2013,2015,3148.537084
5,476689,Bike (low price),NM,0.00,0.000000,2017,2016,2148.753222
6,363191,Bike (low price),NM,0.00,0.000000,2014,2016,2162.827081
7,377372,Family car,G,0.05,127.250000,2017,2016,3160.442649
8,377372,Bike (low price),NM,0.00,0.000000,2017,2015,3160.442649
9,398396,Luxury car,GSL,0.07,179.250000,2018,2014,7877.442677
10,144177,City-car,GSL,0.04,107.083333,2010,2018,1489.624233
11,144177,Bike (low price),NM,0.00,0.000000,2013,2013,1489.624233
12,181213,SUV - compact,GSL,0.05,128.200000,2011,2013,1397.012619
13,181213,Bike (low price),NM,0.00,0.000000,2010,2015,1397.012619
14,305595,Luxury car,GSL,0.07,179.250000,2013,2013,2280.624164
15,305595,Bike (low price),NM,0.00,0.000000,2017,2012,2280.624164
16,305595,SUV - compact,PD,0.03,128.200000,2011,2018,2280.624164
17,337822,Motorbike,G,0.02,107.000000,2016,2010,4107.105183
18,337822,City-car,GSL,0.04,107.083333,2015,2012,4107.105183
19,448184,Motorbike,G,0.02,107.000000,2013,2010,983.406423

In [14]:
df1[df1["Powertrain"] == "E"]

,ID,Type_Of_Vehicle,Powertrain,Cons,CO2,Year_Of_Immatriculation,Year_Of_Purchase,Weight_To_Universe
406,477928,City-car,E,0.12,0.0,2015,2012,3767.453590
460,287620,SUV - compact,E,0.22,0.0,2014,2014,2708.066207
779,256511,Mini-car / quadricycles,E,0.10,0.0,2015,2011,1396.523560
787,171806,Luxury car,E,0.25,0.0,2011,2011,587.420389
850,114457,Family car,E,0.21,0.0,2017,2013,1339.074863
1031,172196,Mini-car / quadricycles,E,0.10,0.0,2018,2010,2329.673336
1062,156175,SUV - compact,E,0.22,0.0,2016,2014,5838.129752
1161,190777,SUV-normal,E,0.24,0.0,2011,2015,1927.113617
1453,186047,SUV - compact,E,0.22,0.0,2012,2017,735.301036
1566,364215,Luxury car,E,0.25,0.0,2017,2012,2061.545236
1600,382456,City-car,E,0.12,0.0,2010,2018,1926.301416
1756,385412,Mini-car / quadricycles,E,0.10,0.0,2014,2010,1527.599418
2007,225836,SUV - compact,E,0.22,0.0,2016,2011,1470.796993
2101,338644,Mini-car / quadricycles,E,0.10,0.0,2013,2016,4038.619677
2222,459040,Family car,E,0.21,0.0,2011,2018,2259.235266
2225,247739,SUV-normal,E,0.24,0.0,2018,2012,3396.625328
2386,208833,City-car,E,0.12,0.0,2013,2012,3636.198650
2425,103521,Family car,E,0.21,0.0,2016,2013,3010.636871
2498,136991,City-car,E,0.12,0.0,2017,2017,1542.453138
2610,395843,SUV-normal,E,0.24,0.0,2011,2012,4096.554567
2725,109615,SUV - compact,E,0.22,0.0,2017,2011,1505.004575
2900,290212,Sporty supercar,E,0.25,0.0,2018,2016,1350.446924
2951,116427,City-car,E,0.12,0.0,2016,2016,2599.559134
3090,480819,Sporty supercar,E,0.25,0.0,2017,2014,1745.330136
3106,371801,City-car,E,0.12,0.0,2015,2016,1823.834199
3110,268269,Family car,E,0.21,0.0,2013,2017,2645.342220
3187,332179,Sporty supercar,E,0.25,0.0,2014,2014,1262.242606
3305,468227,Family car,E,0.21,0.0,2016,2011,4170.617415
3308,211089,Sporty supercar,E,0.25,0.0,2013,2012,1269.621316
3544,140609,Luxury car,E,0.25,0.0,2010,2018,3225.609660
3601,412075,SUV - compact,E,0.22,0.0,2013,2010,1549.638804
3744,139857,Sporty supercar,E,0.25,0.0,2011,2015,3906.351500
3773,131789,Sporty supercar,E,0.25,0.0,2016,2010,1800.246966
3833,467039,Mini-car / quadricycles,E,0.10,0.0,2017,2018,834.116311
3961,157325,Family car,E,0.21,0.0,2017,2014,490.647189
3966,127726,Mini-car / quadricycles,E,0.10,0.0,2018,2015,1321.032490
4052,425053,SUV - compact,E,0.22,0.0,2017,2014,4718.759055
4055,300726,Luxury car,E,0.25,0.0,2010,2017,4353.454399
4076,460166,SUV - compact,E,0.22,0.0,2018,2013,2100.411862
4144,484863,Family car,E,0.21,0.0,2011,2016,519.179034
4451,154169,Family car,E,0.21,0.0,2014,2011,2885.146432
4523,348357,Sporty supercar,E,0.25,0.0,2010,2015,7569.561828
4739,212558,SUV-normal,E,0.24,0.0,2011,2012,1131.997772
4764,432087,Mini-car / quadricycles,E,0.10,0.0,2018,2012,3129.447679

In [5]:
df2.head(10)

       ID  Weight_To_Universe  Car_Sharing  Bike_Sharing
0  100067         2148.356922            0             0
1  100072         1272.129441            0             0
2  100095         1194.770227            0             0
3  100325         1418.254666            0             0
4  100377         1224.849454            0             0
5  100423         3957.258209            0             0
6  100457         1893.943746            0             0
7  100640         3165.579296            0             0
8  100673         1941.219385            0             0
9  100745         1962.885746            0             0

In [6]:
df3 = df3.sort_values(["AgentID", "Time_Start"])

In [12]:
temp = df3[["AgentID", 
     "gemeindetype", 
     "Kanton", 
     "Day_Of_The_Week", 
     "Mode", 
     "Distance", 
     "Vehicle_Category", 
     "Vehicle_Type", 
     "Weight_To_Universe"]].groupby(["AgentID", 
                                     "gemeindetype",
                                     "Kanton",
                                     "Day_Of_The_Week", 
                                     "Mode",
                                     "Vehicle_Category", 
                                     "Vehicle_Type"]).agg({"Distance" : "sum", 
                                                           "Weight_To_Universe" : "mean"}).reset_index()

temp = temp.groupby(["AgentID", 
                     "gemeindetype",
                     "Kanton",
                     "Mode",
                     "Vehicle_Category",
                     "Vehicle_Type"]).agg({"Distance" : "mean", 
                                           "Weight_To_Universe" : "mean"}).reset_index()

temp = temp[temp["Mode"] == "Car"].reset_index(drop=True)
temp

,AgentID,gemeindetype,Kanton,Mode,Vehicle_Category,Vehicle_Type,Weight_To_Universe,Distance
0,100072,1,21,Car,City-car,G,1272,92.70
1,100325,2,3,Car,City-car,G,1418,16.06
2,100377,1,24,Car,City-car,PGSL,1225,1.21
3,100423,6,2,Car,City-car,G,3957,67.58
4,100640,1,12,Car,Family car,G,3166,4.39
5,100745,4,11,Car,SUV - compact,G,1963,10.57
6,101102,1,20,Car,Family car,G,3228,115.84
7,101299,1,24,Car,Family car,G,753,18.09
8,101326,2,1,Car,Luxury car,GSL,5799,11.64
9,101339,2,25,Car,Family car,G,1491,76.70
10,101352,2,2,Car,City-car,G,2182,7.52
11,101485,4,14,Car,Executive car,G,1049,163.91
12,101663,3,13,Car,City-car,G,2465,1.41
13,101768,2,20,Car,Family car,G,1589,65.08
14,101910,5,18,Car,City-car,G,2285,8.66
15,102075,4,22,Car,City-car,G,1350,8.71
16,102084,6,2,Car,City-car,G,4390,1.45
17,102195,1,22,Car,SUV - compact,GSL,1707,6.73
18,102294,4,11,Car,SUV-normal,G,2539,50.15
19,102300,1,1,Car,City-car,G,2202,38.45
20,102552,2,25,Car,Family car,G,1445,14.00
21,102575,2,3,Car,Executive car,G,3107,24.43
22,102592,2,3,Car,Family car,G,1480,172.44
23,102724,8,2,Car,SUV-normal,G,10193,14.86
24,102924,8,2,Car,Executive car,G,5570,22.85
25,102987,4,19,Car,SUV-normal,G,1283,83.64
26,103122,2,19,Car,City-car,G,1162,30.90
27,103212,1,9,Car,SUV-normal,G,1861,5.36
28,103247,2,1,Car,City-car,G,6806,16.08
29,103320,4,23,Car,SUV-normal,G,3347,15.13
...,...,...,...,...,...,...,...,...
2166,490884,2,18,Car,SUV-normal,G,1967,177.11
2167,490990,4,5,Car,SUV - compact,HG,1537,75.56
2168,491336,1,1,Car,SUV-normal,GSL,7304,13.78
2169,491447,9,2,Car,City-car,G,3077,23.63
2170,491677,2,2,Car,City-car,G,2531,11.63
2171,491785,6,23,Car,City-car,G,3326,24.45
2172,491981,2,10,Car,Family car,G,1657,29.74
2173,492040,7,22,Car,City-car,G,1923,42.65
2174,492358,1,24,Car,City-car,G,654,1.76
2175,492535,1,19,Car,City-car,G,1514,32.86
2176,492670,2,1,Car,Family car,G,3861,14.90
2177,492992,1,2,Car,Family car,G,1955,12.56
2178,493468,2,1,Car,Sporty supercar,GSL,2914,2.18
2179,493759,1,1,Car,SUV-normal,G,3767,42.95
2180,493858,8,3,Car,Executive car,D,1474,22.33
2181,494410,2,2,Car,Family car,G,2330,88.48
2182,494421,1,12,Car,City-car,G,3914,21.29
2183,494478,2,25,Car,City-car,G,2332,19.92
2184,494488,2,3,Car,Executive car,G,1350,75.23
2185,495692,2,19,Car,City-car,G,1072,256.95
2186,496800,2,1,Car,City-car,G,3580,39.73
2187,496998,1,8,Car,Executive car,G,3696,6.80
2188,497082,2,10,Car,City-car,G,1571,38.77
2189,497098,2,17,Car,Family car,G,4358,51.10
2190,497617,1,17,Car,Family car,GSL,5485,94.11
2191,497625,1,10,Car,City-car,G,1642,3.50
2192,497649,2,10,Car,City-car,GSL,1632,100.21
2193,497668,1,22,Car,Family car,E,3226,7.49
2194,498324,7,23,Car,Family car,G,1486,152.18
2195,499786,2,1,Car,Executive car,GSL,8869,98.07

In [5]:
df3[(df3["AgentID"] == 100067) & (df3["Day_Of_The_Week"] == 0)]

,AgentID,gemeindetype,Kanton,Day_Of_The_Week,Time_Start,Distance,Purpose,Mode,Vehicle_Category,Vehicle_Type,Weather,Weight_To_Universe
17,100067,1,12,0,11.00,0.60,4,Bike,Bike (low price),NM,good,2148
19,100067,1,12,0,22.00,1.06,8,Bike,Bike (low price),NM,good,2148
23,100067,1,12,0,19.00,1.05,8,Walk,Walking,NM,good,2148
26,100067,1,12,0,11.25,0.60,4,Bike,Bike (low price),NM,good,2148

In [8]:
df3[(df3["AgentID"] == 499384) & (df3["Day_Of_The_Week"] == 1)]

,AgentID,gemeindetype,Kanton,Day_Of_The_Week,Time_Start,Distance,Purpose,Mode,Vehicle_Category,Vehicle_Type,Weather,Weight_To_Universe
90983,499384,1,10,1,13.0,0.73,4,Bike,Bike (low price),NM,good,2261
90971,499384,1,10,1,13.3,0.29,8,Bike,Bike (low price),NM,good,2261
90985,499384,1,10,1,15.0,0.73,8,Bike,Bike (low price),NM,good,2261

In [10]:
df3[(df3["AgentID"] == 499384) & (df3["Day_Of_The_Week"] == 2)]

,AgentID,gemeindetype,Kanton,Day_Of_The_Week,Time_Start,Distance,Purpose,Mode,Vehicle_Category,Vehicle_Type,Weather,Weight_To_Universe
90975,499384,1,10,2,13.0,0.73,4,Bike,Bike (low price),NM,good,2261
90980,499384,1,10,2,13.3,0.29,8,Bike,Bike (low price),NM,good,2261
90966,499384,1,10,2,15.0,0.73,8,Bike,Bike (low price),NM,good,2261

In [20]:
len(df.AgentID.unique())

2844

In [21]:
agendIds = df["AgentID"]

In [22]:
agendIds.head()

0    2306
1    2304
2    2303
3    2302
4    2301
Name: AgentID, dtype: int64

In [25]:
df[agendIds.isin(agendIds[agendIds.duplicated()])]

,AgentID,Kanton,TimeStart,Distance,Purpose,Mode,Vehicle_Category,Vehicle_Type,Weather,Weight_To_Universe
311,1941,11,23,205,L,Car,Executive,G,good,10788
312,1941,3,0,25,L,Car,Executive,G,good,10788
1232,1353,20,9,30,L,Rail,Train,E,good,2024
1233,1353,23,0,33,L,Rail,Train,E,good,2024
2569,2239,0,16,47,L,Car,City-car,G,good,2779
2570,2239,6,0,40,L,Car,City-car,G,good,2779
2808,1857,24,5,8,L,Car,Family car,G,good,24781
2809,1857,16,0,20,L,Tram-Bus,Bus,G,good,24781