In [1]:
import pandas as pd
import numpy as np
import vptree as vp

In [5]:
df_beddem_trips = pd.read_csv("/home/ctchervenkov/git/JA_Mobility_exchange/BEDDEM-MATSIM/03-trips.2015.csv")
df_beddem_trips.head()

,AgentID,gemeindetype,Kanton,Day_Of_The_Week,Time_Start,Distance,Purpose,Mode,Vehicle_Category,Vehicle_Type,Weather,Weight_To_Universe
0,100067,1,12,4,11.25,0.60,4,Bike,Bike (low price),NM,good,2148
1,100067,1,12,3,11.00,0.60,4,Bike,Bike (low price),NM,good,2148
2,100067,1,12,2,11.00,0.60,4,Bike,Bike (low price),NM,good,2148
3,100067,1,12,2,19.00,1.05,8,Walk,Walking,NM,good,2148
4,100067,1,12,4,11.00,0.60,4,Bike,Bike (low price),NM,good,2148

In [7]:
df_matsim_trips = pd.read_csv("/home/ctchervenkov/Documents/data/scenarios/switzerland_2018_10pct/output_trips.csv", sep=";")
df_matsim_trips.head()

,person_id,person_trip_id,origin_x,origin_y,destination_x,destination_y,start_time,travel_time,network_distance,mode,preceedingPurpose,followingPurpose,returning,crowfly_distance
0,7607985,0,2.595848e+06,1.123250e+06,2.595975e+06,1.123398e+06,0.0,70.0,0.414224,car,home,work,False,0.194511
1,3956472,0,2.611620e+06,1.268165e+06,2.612095e+06,1.268386e+06,0.0,144.0,0.823471,car,home,work,False,0.524534
2,1346393,0,2.681438e+06,1.246555e+06,2.681478e+06,1.247443e+06,0.0,178.0,1.173595,car,home,work,False,0.888177
3,3318350,0,2.682222e+06,1.224801e+06,2.681532e+06,1.225181e+06,0.0,202.0,1.613966,car,home,work,False,0.787492
4,3082912,0,2.692071e+06,1.208145e+06,2.690956e+06,1.208971e+06,0.0,221.0,1.938969,car,home,work,False,1.387174

In [10]:
df_matsim_trips_car = df_matsim_trips[df_matsim_trips["mode"] == "car"]

In [12]:
df_matsim_total_distances = df_matsim_trips_car[["person_id","network_distance"]].groupby("person_id").sum().reset_index()

In [14]:
print(df_matsim_total_distances["network_distance"].mean())

43.04061704141353